2024-11-03 16:40:43,423 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-11-03 16:40:43,425 [33mPress CTRL+C to quit[0m
2024-11-03 16:40:43,447  * Restarting with watchdog (windowsapi)
2024-11-03 16:40:44,867  * Debugger is active!
2024-11-03 16:40:44,874  * Debugger PIN: 371-600-436
2024-11-03 16:41:17,089  * Detected change in 'C:\\Python312\\Lib\\fileinput.py', reloading
2024-11-03 16:41:17,487  * Detected change in 'C:\\Python312\\Lib\\unittest\\__init__.py', reloading
2024-11-03 16:41:17,499  * Detected change in 'C:\\Python312\\Lib\\unittest\\result.py', reloading
2024-11-03 16:41:17,507  * Detected change in 'C:\\Python312\\Lib\\unittest\\util.py', reloading
2024-11-03 16:41:17,529  * Detected change in 'C:\\Python312\\Lib\\unittest\\case.py', reloading
2024-11-03 16:41:17,667  * Restarting with watchdog (windowsapi)
2024-11-03 16:41:18,897  * Debugger is active!
2024-11-03 16:41:18,897  * Debugger PIN: 371-600-436
2024-11-03 16:41:19,108  * Detected change in 'C:\\Python312\\Lib\\unittest\\suite.py', reloading
2024-11-03 16:41:19,127  * Detected change in 'C:\\Python312\\Lib\\unittest\\loader.py', reloading
2024-11-03 16:41:19,137  * Detected change in 'C:\\Python312\\Lib\\unittest\\main.py', reloading
2024-11-03 16:41:19,147  * Detected change in 'C:\\Python312\\Lib\\unittest\\runner.py', reloading
2024-11-03 16:41:19,157  * Detected change in 'C:\\Python312\\Lib\\unittest\\signals.py', reloading
2024-11-03 16:41:20,127  * Restarting with watchdog (windowsapi)
2024-11-03 16:41:21,517  * Debugger is active!
2024-11-03 16:41:21,517  * Debugger PIN: 371-600-436
2024-11-03 16:41:25,317  * Detected change in 'C:\\Python312\\Lib\\_strptime.py', reloading
2024-11-03 16:41:25,947  * Restarting with watchdog (windowsapi)
2024-11-03 16:41:27,347  * Debugger is active!
2024-11-03 16:41:27,357  * Debugger PIN: 371-600-436
2024-11-03 16:41:29,428  * Detected change in 'C:\\Python312\\Lib\\ctypes\\util.py', reloading
2024-11-03 16:41:29,747  * Restarting with watchdog (windowsapi)
2024-11-03 16:41:31,227  * Debugger is active!
2024-11-03 16:41:31,232  * Debugger PIN: 371-600-436
2024-11-03 16:41:34,215  * Detected change in 'C:\\Python312\\Lib\\encodings\\latin_1.py', reloading
2024-11-03 16:41:34,447 All predictive models loaded successfully
2024-11-03 16:41:34,447 127.0.0.1 - - [03/Nov/2024 16:41:34] "OPTIONS /login HTTP/1.1" 200 -
2024-11-03 16:41:34,457 All predictive models loaded successfully
2024-11-03 16:41:34,457 127.0.0.1 - - [03/Nov/2024 16:41:34] "OPTIONS /login HTTP/1.1" 200 -
2024-11-03 16:41:34,767  * Restarting with watchdog (windowsapi)
2024-11-03 16:41:36,295  * Debugger is active!
2024-11-03 16:41:36,297  * Debugger PIN: 371-600-436
2024-11-03 16:42:02,581 All predictive models loaded successfully
2024-11-03 16:42:02,581 127.0.0.1 - - [03/Nov/2024 16:42:02] "OPTIONS /login HTTP/1.1" 200 -
2024-11-03 16:42:02,967 127.0.0.1 - - [03/Nov/2024 16:42:02] "POST /login HTTP/1.1" 200 -
2024-11-03 16:42:03,199 127.0.0.1 - - [03/Nov/2024 16:42:03] "OPTIONS /users HTTP/1.1" 200 -
2024-11-03 16:42:03,227 127.0.0.1 - - [03/Nov/2024 16:42:03] "GET /users HTTP/1.1" 200 -
2024-11-03 16:42:03,259 127.0.0.1 - - [03/Nov/2024 16:42:03] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 16:42:03,277 127.0.0.1 - - [03/Nov/2024 16:42:03] "GET /patients HTTP/1.1" 200 -
2024-11-03 16:42:20,323 127.0.0.1 - - [03/Nov/2024 16:42:20] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 16:42:20,337 127.0.0.1 - - [03/Nov/2024 16:42:20] "GET /patients HTTP/1.1" 200 -
2024-11-03 17:19:28,000 127.0.0.1 - - [03/Nov/2024 17:19:28] "OPTIONS /users HTTP/1.1" 200 -
2024-11-03 17:19:28,030 127.0.0.1 - - [03/Nov/2024 17:19:28] "GET /users HTTP/1.1" 200 -
2024-11-03 17:19:28,040 127.0.0.1 - - [03/Nov/2024 17:19:28] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 17:19:28,055 127.0.0.1 - - [03/Nov/2024 17:19:28] "GET /patients HTTP/1.1" 200 -
2024-11-03 17:19:31,290 127.0.0.1 - - [03/Nov/2024 17:19:31] "GET /patients HTTP/1.1" 200 -
2024-11-03 17:19:34,350 127.0.0.1 - - [03/Nov/2024 17:19:34] "OPTIONS /users HTTP/1.1" 200 -
2024-11-03 17:19:34,366 127.0.0.1 - - [03/Nov/2024 17:19:34] "GET /users HTTP/1.1" 200 -
2024-11-03 17:19:34,381 127.0.0.1 - - [03/Nov/2024 17:19:34] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 17:19:34,400 127.0.0.1 - - [03/Nov/2024 17:19:34] "GET /patients HTTP/1.1" 200 -
2024-11-03 17:19:36,550 127.0.0.1 - - [03/Nov/2024 17:19:36] "OPTIONS /audit-log HTTP/1.1" 200 -
2024-11-03 17:19:36,560 127.0.0.1 - - [03/Nov/2024 17:19:36] "GET /audit-log HTTP/1.1" 200 -
2024-11-03 17:19:49,230 Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-03 17:19:49,250  * Detected change in 'C:\\Users\\felip\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\app.py', reloading
2024-11-03 17:19:49,290 127.0.0.1 - - [03/Nov/2024 17:19:49] "[35m[1mOPTIONS /patients/:id HTTP/1.1[0m" 500 -
2024-11-03 17:19:49,290  * Detected change in 'C:\\Users\\felip\\AppData\\Roaming\\Python\\Python312\\site-packages\\flask\\ctx.py', reloading
2024-11-03 17:19:49,290  * Detected change in 'C:\\Users\\felip\\AppData\\Roaming\\Python\\Python312\\site-packages\\werkzeug\\routing\\map.py', reloading
2024-11-03 17:19:49,611  * Restarting with watchdog (windowsapi)
2024-11-03 17:19:50,940  * Debugger is active!
2024-11-03 17:19:50,945  * Debugger PIN: 371-600-436
2024-11-03 17:20:03,990 All predictive models loaded successfully
2024-11-03 17:20:03,990 127.0.0.1 - - [03/Nov/2024 17:20:03] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 17:20:04,050 127.0.0.1 - - [03/Nov/2024 17:20:04] "GET /patients HTTP/1.1" 200 -
2024-11-03 17:20:13,222 127.0.0.1 - - [03/Nov/2024 17:20:13] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 17:20:13,237 127.0.0.1 - - [03/Nov/2024 17:20:13] "GET /patients HTTP/1.1" 200 -
2024-11-03 17:20:17,523 127.0.0.1 - - [03/Nov/2024 17:20:17] "OPTIONS /user/me HTTP/1.1" 200 -
2024-11-03 17:20:17,534 127.0.0.1 - - [03/Nov/2024 17:20:17] "GET /user/me HTTP/1.1" 200 -
2024-11-03 17:20:31,980 127.0.0.1 - - [03/Nov/2024 17:20:31] "OPTIONS /user/me HTTP/1.1" 200 -
2024-11-03 17:20:32,000 127.0.0.1 - - [03/Nov/2024 17:20:32] "GET /user/me HTTP/1.1" 200 -
2024-11-03 17:20:35,820 127.0.0.1 - - [03/Nov/2024 17:20:35] "GET /user/me HTTP/1.1" 200 -
2024-11-03 17:20:39,205 127.0.0.1 - - [03/Nov/2024 17:20:39] "OPTIONS /user/me HTTP/1.1" 200 -
2024-11-03 17:20:39,210 127.0.0.1 - - [03/Nov/2024 17:20:39] "GET /user/me HTTP/1.1" 200 -
2024-11-03 17:27:21,336 127.0.0.1 - - [03/Nov/2024 17:27:21] "OPTIONS /user/me HTTP/1.1" 200 -
2024-11-03 17:27:21,544 127.0.0.1 - - [03/Nov/2024 17:27:21] "GET /user/me HTTP/1.1" 200 -
2024-11-03 17:31:23,630 127.0.0.1 - - [03/Nov/2024 17:31:23] "OPTIONS /user/me HTTP/1.1" 200 -
2024-11-03 17:31:23,642 127.0.0.1 - - [03/Nov/2024 17:31:23] "GET /user/me HTTP/1.1" 200 -
2024-11-03 17:36:24,627 127.0.0.1 - - [03/Nov/2024 17:36:24] "OPTIONS /user/me HTTP/1.1" 200 -
2024-11-03 17:36:24,659 127.0.0.1 - - [03/Nov/2024 17:36:24] "GET /user/me HTTP/1.1" 200 -
2024-11-03 17:37:16,071 127.0.0.1 - - [03/Nov/2024 17:37:16] "OPTIONS /user/me HTTP/1.1" 200 -
2024-11-03 17:37:16,329 127.0.0.1 - - [03/Nov/2024 17:37:16] "GET /user/me HTTP/1.1" 200 -
2024-11-03 17:37:34,095 127.0.0.1 - - [03/Nov/2024 17:37:34] "OPTIONS /user/me HTTP/1.1" 200 -
2024-11-03 17:37:34,402 127.0.0.1 - - [03/Nov/2024 17:37:34] "GET /user/me HTTP/1.1" 200 -
2024-11-03 18:00:10,117 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-11-03 18:00:10,117 [33mPress CTRL+C to quit[0m
2024-11-03 18:00:10,150  * Restarting with watchdog (windowsapi)
2024-11-03 18:00:12,659  * Debugger is active!
2024-11-03 18:00:12,659  * Debugger PIN: 371-600-436
2024-11-03 18:16:33,004  * Detected change in 'C:\\Python312\\Lib\\fileinput.py', reloading
2024-11-03 18:16:33,067  * Detected change in 'C:\\Python312\\Lib\\unittest\\__init__.py', reloading
2024-11-03 18:16:33,067  * Detected change in 'C:\\Python312\\Lib\\unittest\\result.py', reloading
2024-11-03 18:16:33,067  * Detected change in 'C:\\Python312\\Lib\\unittest\\util.py', reloading
2024-11-03 18:16:33,083  * Detected change in 'C:\\Python312\\Lib\\unittest\\case.py', reloading
2024-11-03 18:16:33,083  * Detected change in 'C:\\Python312\\Lib\\unittest\\suite.py', reloading
2024-11-03 18:16:33,083  * Detected change in 'C:\\Python312\\Lib\\unittest\\loader.py', reloading
2024-11-03 18:16:33,083  * Detected change in 'C:\\Python312\\Lib\\unittest\\main.py', reloading
2024-11-03 18:16:33,099  * Detected change in 'C:\\Python312\\Lib\\unittest\\runner.py', reloading
2024-11-03 18:16:33,100  * Detected change in 'C:\\Python312\\Lib\\unittest\\signals.py', reloading
2024-11-03 18:16:33,683  * Restarting with watchdog (windowsapi)
2024-11-03 18:16:35,086  * Debugger is active!
2024-11-03 18:16:35,086  * Debugger PIN: 371-600-436
2024-11-03 18:16:36,033  * Detected change in 'C:\\Python312\\Lib\\_strptime.py', reloading
2024-11-03 18:16:36,349  * Restarting with watchdog (windowsapi)
2024-11-03 18:16:37,753  * Debugger is active!
2024-11-03 18:16:37,753  * Debugger PIN: 371-600-436
2024-11-03 18:16:39,268  * Detected change in 'C:\\Python312\\Lib\\ctypes\\util.py', reloading
2024-11-03 18:16:39,567  * Detected change in 'C:\\Python312\\Lib\\encodings\\latin_1.py', reloading
2024-11-03 18:16:39,726 All predictive models loaded successfully
2024-11-03 18:16:39,726 127.0.0.1 - - [03/Nov/2024 18:16:39] "OPTIONS /login HTTP/1.1" 200 -
2024-11-03 18:16:39,726 All predictive models loaded successfully
2024-11-03 18:16:39,726 127.0.0.1 - - [03/Nov/2024 18:16:39] "OPTIONS /login HTTP/1.1" 200 -
2024-11-03 18:16:40,280  * Restarting with watchdog (windowsapi)
2024-11-03 18:16:41,600  * Debugger is active!
2024-11-03 18:16:41,600  * Debugger PIN: 371-600-436
2024-11-03 18:16:49,835 All predictive models loaded successfully
2024-11-03 18:16:49,835 127.0.0.1 - - [03/Nov/2024 18:16:49] "OPTIONS /login HTTP/1.1" 200 -
2024-11-03 18:16:50,167 127.0.0.1 - - [03/Nov/2024 18:16:50] "POST /login HTTP/1.1" 200 -
2024-11-03 18:16:50,399 127.0.0.1 - - [03/Nov/2024 18:16:50] "OPTIONS /users HTTP/1.1" 200 -
2024-11-03 18:16:50,404 127.0.0.1 - - [03/Nov/2024 18:16:50] "GET /users HTTP/1.1" 200 -
2024-11-03 18:16:50,420 127.0.0.1 - - [03/Nov/2024 18:16:50] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 18:16:50,435 127.0.0.1 - - [03/Nov/2024 18:16:50] "GET /patients HTTP/1.1" 200 -
2024-11-03 18:16:56,623 127.0.0.1 - - [03/Nov/2024 18:16:56] "OPTIONS /audit-log HTTP/1.1" 200 -
2024-11-03 18:16:56,639 127.0.0.1 - - [03/Nov/2024 18:16:56] "GET /audit-log HTTP/1.1" 200 -
2024-11-03 18:16:58,765 127.0.0.1 - - [03/Nov/2024 18:16:58] "OPTIONS /users HTTP/1.1" 200 -
2024-11-03 18:16:58,781 127.0.0.1 - - [03/Nov/2024 18:16:58] "GET /users HTTP/1.1" 200 -
2024-11-03 18:16:58,796 127.0.0.1 - - [03/Nov/2024 18:16:58] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 18:16:58,812 127.0.0.1 - - [03/Nov/2024 18:16:58] "GET /patients HTTP/1.1" 200 -
2024-11-03 18:17:04,147 127.0.0.1 - - [03/Nov/2024 18:17:04] "OPTIONS /audit-log HTTP/1.1" 200 -
2024-11-03 18:17:04,162 127.0.0.1 - - [03/Nov/2024 18:17:04] "GET /audit-log HTTP/1.1" 200 -
2024-11-03 18:17:08,228 Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-03 18:17:08,228 127.0.0.1 - - [03/Nov/2024 18:17:08] "[35m[1mOPTIONS /patients/:id HTTP/1.1[0m" 500 -
2024-11-03 18:17:27,555 127.0.0.1 - - [03/Nov/2024 18:17:27] "OPTIONS /users HTTP/1.1" 200 -
2024-11-03 18:17:27,572 127.0.0.1 - - [03/Nov/2024 18:17:27] "GET /users HTTP/1.1" 200 -
2024-11-03 18:17:27,587 127.0.0.1 - - [03/Nov/2024 18:17:27] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 18:17:27,603 127.0.0.1 - - [03/Nov/2024 18:17:27] "GET /patients HTTP/1.1" 200 -
2024-11-03 18:17:28,050 127.0.0.1 - - [03/Nov/2024 18:17:28] "OPTIONS /audit-log HTTP/1.1" 200 -
2024-11-03 18:17:28,050 127.0.0.1 - - [03/Nov/2024 18:17:28] "GET /audit-log HTTP/1.1" 200 -
2024-11-03 18:17:29,205 Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-03 18:17:29,205 127.0.0.1 - - [03/Nov/2024 18:17:29] "[35m[1mOPTIONS /patients/:id HTTP/1.1[0m" 500 -
2024-11-03 18:17:31,944 Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-03 18:17:31,944 127.0.0.1 - - [03/Nov/2024 18:17:31] "[35m[1mOPTIONS /patients/:id HTTP/1.1[0m" 500 -
2024-11-03 18:17:32,879 127.0.0.1 - - [03/Nov/2024 18:17:32] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 18:17:32,894 127.0.0.1 - - [03/Nov/2024 18:17:32] "GET /patients HTTP/1.1" 200 -
2024-11-03 18:17:34,155 127.0.0.1 - - [03/Nov/2024 18:17:34] "OPTIONS /user/me HTTP/1.1" 200 -
2024-11-03 18:17:34,179 127.0.0.1 - - [03/Nov/2024 18:17:34] "GET /user/me HTTP/1.1" 200 -
2024-11-03 18:17:47,931 127.0.0.1 - - [03/Nov/2024 18:17:47] "OPTIONS /users HTTP/1.1" 200 -
2024-11-03 18:17:47,946 127.0.0.1 - - [03/Nov/2024 18:17:47] "GET /users HTTP/1.1" 200 -
2024-11-03 18:17:48,422 127.0.0.1 - - [03/Nov/2024 18:17:48] "OPTIONS /user/me HTTP/1.1" 200 -
2024-11-03 18:17:48,438 127.0.0.1 - - [03/Nov/2024 18:17:48] "GET /user/me HTTP/1.1" 200 -
2024-11-03 18:17:48,833 127.0.0.1 - - [03/Nov/2024 18:17:48] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 18:17:48,855 127.0.0.1 - - [03/Nov/2024 18:17:48] "GET /patients HTTP/1.1" 200 -
2024-11-03 18:17:51,112 Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-03 18:17:51,112 127.0.0.1 - - [03/Nov/2024 18:17:51] "[35m[1mOPTIONS /patients/:id HTTP/1.1[0m" 500 -
2024-11-03 18:17:52,184 127.0.0.1 - - [03/Nov/2024 18:17:52] "OPTIONS /audit-log HTTP/1.1" 200 -
2024-11-03 18:17:52,200 127.0.0.1 - - [03/Nov/2024 18:17:52] "GET /audit-log HTTP/1.1" 200 -
2024-11-03 18:17:52,595 127.0.0.1 - - [03/Nov/2024 18:17:52] "GET /users HTTP/1.1" 200 -
2024-11-03 18:17:52,626 127.0.0.1 - - [03/Nov/2024 18:17:52] "GET /patients HTTP/1.1" 200 -
2024-11-03 18:18:09,792 127.0.0.1 - - [03/Nov/2024 18:18:09] "OPTIONS /audit-log HTTP/1.1" 200 -
2024-11-03 18:18:09,807 127.0.0.1 - - [03/Nov/2024 18:18:09] "GET /audit-log HTTP/1.1" 200 -
2024-11-03 18:18:10,473 127.0.0.1 - - [03/Nov/2024 18:18:10] "OPTIONS /users HTTP/1.1" 200 -
2024-11-03 18:18:10,489 127.0.0.1 - - [03/Nov/2024 18:18:10] "GET /users HTTP/1.1" 200 -
2024-11-03 18:18:10,489 127.0.0.1 - - [03/Nov/2024 18:18:10] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 18:18:10,506 127.0.0.1 - - [03/Nov/2024 18:18:10] "GET /patients HTTP/1.1" 200 -
2024-11-03 18:18:15,078 127.0.0.1 - - [03/Nov/2024 18:18:15] "OPTIONS /audit-log HTTP/1.1" 200 -
2024-11-03 18:18:15,094 127.0.0.1 - - [03/Nov/2024 18:18:15] "GET /audit-log HTTP/1.1" 200 -
2024-11-03 18:18:20,497 127.0.0.1 - - [03/Nov/2024 18:18:20] "OPTIONS /audit-log HTTP/1.1" 200 -
2024-11-03 18:18:20,513 127.0.0.1 - - [03/Nov/2024 18:18:20] "GET /audit-log HTTP/1.1" 200 -
2024-11-03 18:18:20,911 127.0.0.1 - - [03/Nov/2024 18:18:20] "OPTIONS /users HTTP/1.1" 200 -
2024-11-03 18:18:20,926 127.0.0.1 - - [03/Nov/2024 18:18:20] "GET /users HTTP/1.1" 200 -
2024-11-03 18:18:20,942 127.0.0.1 - - [03/Nov/2024 18:18:20] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 18:18:20,946 127.0.0.1 - - [03/Nov/2024 18:18:20] "GET /patients HTTP/1.1" 200 -
2024-11-03 18:18:23,224 Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Roaming\Python\Python312\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-03 18:18:23,224 127.0.0.1 - - [03/Nov/2024 18:18:23] "[35m[1mOPTIONS /patients/:id HTTP/1.1[0m" 500 -
2024-11-03 18:18:24,529 127.0.0.1 - - [03/Nov/2024 18:18:24] "GET /users HTTP/1.1" 200 -
2024-11-03 18:18:24,560 127.0.0.1 - - [03/Nov/2024 18:18:24] "GET /patients HTTP/1.1" 200 -
2024-11-03 18:18:25,767 127.0.0.1 - - [03/Nov/2024 18:18:25] "GET /users HTTP/1.1" 200 -
2024-11-03 18:18:29,409 127.0.0.1 - - [03/Nov/2024 18:18:29] "OPTIONS /audit-log HTTP/1.1" 200 -
2024-11-03 18:18:29,425 127.0.0.1 - - [03/Nov/2024 18:18:29] "GET /audit-log HTTP/1.1" 200 -
2024-11-03 18:20:00,429 127.0.0.1 - - [03/Nov/2024 18:20:00] "OPTIONS /audit-log HTTP/1.1" 200 -
2024-11-03 18:20:00,634 127.0.0.1 - - [03/Nov/2024 18:20:00] "GET /audit-log HTTP/1.1" 200 -
2024-11-03 18:25:51,487 127.0.0.1 - - [03/Nov/2024 18:25:51] "OPTIONS /users HTTP/1.1" 200 -
2024-11-03 18:25:51,503 127.0.0.1 - - [03/Nov/2024 18:25:51] "GET /users HTTP/1.1" 200 -
2024-11-03 18:25:51,503 127.0.0.1 - - [03/Nov/2024 18:25:51] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 18:25:51,535 127.0.0.1 - - [03/Nov/2024 18:25:51] "GET /patients HTTP/1.1" 200 -
2024-11-03 18:30:25,844 127.0.0.1 - - [03/Nov/2024 18:30:25] "OPTIONS /users HTTP/1.1" 200 -
2024-11-03 18:30:26,107 127.0.0.1 - - [03/Nov/2024 18:30:26] "GET /users HTTP/1.1" 200 -
2024-11-03 18:30:26,144 127.0.0.1 - - [03/Nov/2024 18:30:26] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 18:30:26,161 127.0.0.1 - - [03/Nov/2024 18:30:26] "GET /patients HTTP/1.1" 200 -
2024-11-03 18:30:31,383 127.0.0.1 - - [03/Nov/2024 18:30:31] "OPTIONS /users HTTP/1.1" 200 -
2024-11-03 18:30:31,470 127.0.0.1 - - [03/Nov/2024 18:30:31] "GET /users HTTP/1.1" 200 -
2024-11-03 18:30:31,667 127.0.0.1 - - [03/Nov/2024 18:30:31] "OPTIONS /patients HTTP/1.1" 200 -
2024-11-03 18:30:31,699 127.0.0.1 - - [03/Nov/2024 18:30:31] "GET /patients HTTP/1.1" 200 -
2024-11-03 19:08:49,829  * Detected change in 'c:\\Users\\felip\\OneDrive\\Documentos\\FATEC\\Sakaue (Projeto LGPD)\\backend-PatientSystem\\app.py', reloading
2024-11-03 19:08:49,844  * Detected change in 'c:\\Users\\felip\\OneDrive\\Documentos\\FATEC\\Sakaue (Projeto LGPD)\\backend-PatientSystem\\auth.py', reloading
2024-11-03 19:08:49,860  * Detected change in 'c:\\Users\\felip\\OneDrive\\Documentos\\FATEC\\Sakaue (Projeto LGPD)\\backend-PatientSystem\\config.py', reloading
2024-11-03 19:08:49,860  * Detected change in 'c:\\Users\\felip\\OneDrive\\Documentos\\FATEC\\Sakaue (Projeto LGPD)\\backend-PatientSystem\\generate_hashed.py', reloading
2024-11-03 19:08:49,876  * Detected change in 'c:\\Users\\felip\\OneDrive\\Documentos\\FATEC\\Sakaue (Projeto LGPD)\\backend-PatientSystem\\models.py', reloading
2024-11-03 19:08:49,876  * Detected change in 'c:\\Users\\felip\\OneDrive\\Documentos\\FATEC\\Sakaue (Projeto LGPD)\\backend-PatientSystem\\schemas.py', reloading
2024-11-03 19:08:49,892  * Detected change in 'c:\\Users\\felip\\OneDrive\\Documentos\\FATEC\\Sakaue (Projeto LGPD)\\backend-PatientSystem\\migrations\\env.py', reloading
2024-11-03 19:08:50,599  * Restarting with watchdog (windowsapi)
2024-11-03 19:08:52,250  * Debugger is active!
2024-11-03 19:08:52,265  * Debugger PIN: 371-600-436
